name: Pull Request 테스트

on:
  pull_request:
    branches: ['*']
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: PNPM 설치
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: 의존성 설치
        run: pnpm install

      - name: 린트 실행
        run: pnpm lint

      - name: 테스트 실행
        run: pnpm test

      - name: 빌드 실행
        run: pnpm build

      - name: 테스트 커버리지 업로드
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: false
          verbose: true
